---

- name: Installing Mysql and dependencies
  apt: name={{item}} state=present  update_cache=yes
  with_items:
      - mysql-server-5.6
      - python-mysqldb

- service: name=mysql state=started

- name: Mysql Secure Installation
  include: mysql_secure_installation.yml 

- name: Change Mysql Data Directory
  include: change_mysql_data_directory.yml
