---

- name: Installing Mysql and dependencies
  apt: name={{item}} state=present  update_cache=yes
  with_items:
      - mysql-server
      - python-mysqldb
  notify: mysql restart

- name: Mysql Secure Installation
  include: mysql_secure_installation.yml 

- name: Allow mysql fro remote host
  template: src=my.conf.j2 dest=/etc/mysql/my.cnf owner=root group=root mode=0644
  notify: mysql restart
